Adds security.md.
canonical/jimm pull request #1379
Opened 2024-10-01 08:13 UTC by alesstimec

## Description

Adds security.md as part of the vulnerability and response.

## Engineering checklist
*Check only items that apply*

- [ ] Documentation updated
- [ ] Covered by unit tests
- [ ] Covered by integration tests

## Test instructions

## Notes for code reviewers

2024-10-01 08:14 UTC, kian99 reviewed
Going to https://github.com/Canonical/jimm/security/advisories/new returns a 404

2024-10-01 08:17 UTC, kian99 approved these changes, later dismissed

2024-10-01 12:05 UTC, ale8k commented
I think this is missing detail, this is really just the temlate they given us but lxd is more in depth.

https://github.com/canonical/lxd/blob/main/SECURITY.md

This is much nicer and also the file name should be capitlised I think...

2024-10-01 12:06 UTC, ale8k requested changes
requesting changes on file name and some details on what we're willing to fix (i.e., versioning)

2024-10-01 12:45 UTC, kian99 commented on SECURITY.md
> +distributions.
This needs fixing to be about JAAS not LXD and the bit at the end about "various Linux distributions" doesn't apply.

2024-10-02 09:10 UTC, ale8k approved these changes
bar kians comment

2024-10-17 08:19 UTC, closed without merging