Juju 7074/identities filter
canonical/jimm pull request #1434
Opened 2024-11-13 13:53 UTC by SimoneDutto

## Description

This pr adds filtering for rebac `listIdentities` on group name/id.

Address #1421 

## Engineering checklist
*Check only items that apply*

- [ ] Documentation updated
- [ ] Covered by unit tests
- [ ] Covered by integration tests

## Test instructions

## Notes for code reviewers

2024-11-13 15:35 UTC, kian99 approved these changes

2024-11-13 15:35 UTC, kian99 commented on internal/testutils/jimmtest/jimm_mock.go
> +	ListIdentities_                    func(ctx context.Context, user *openfga.User, filter pagination.LimitOffsetPagination, match string) ([]openfga.User, error)
nit: rename `filter` here to `pagination` as well.

2024-11-13 15:35 UTC, kian99 commented on internal/jimmhttp/rebac_admin/identities_test.go
> +		ListIdentities_: func(ctx context.Context, user *openfga.User, filter pagination.LimitOffsetPagination, match string) ([]openfga.User, error) {
nit: Rename `filter` to `pagination` as well.

2024-11-15 07:33 UTC, ale8k requested changes
I need to request changes so we can remove the space but ping me once done and I'll approve (justh ave a think about my other comment)

2024-11-15 07:33 UTC, ale8k commented on internal/jimm/identity.go
> +	var users []openfga.User
Feel like I'm reading that book aha. Love it.

2024-11-15 07:33 UTC, ale8k commented on internal/jimm/identity_test.go
> +			match:      userNames[0][:5],
As we're reating another slice anyway rather than just [:1], either do: [:1] on 117 or hardcode the string in please. 

I'm usually of the preference of hardcoding strings in tests as I feel like it makes them more readable rather than bob1->5. Also as this is a match, doing [0] and [:5] against a string is less readable (imo) than just getting "bob1".

2024-11-15 07:33 UTC, ale8k commented on internal/jimmhttp/rebac_admin/identities_integration_test.go
> +
Extra space

2024-11-15 07:52 UTC, ale8k approved these changes
lgtm

2024-11-15 08:30 UTC, merged