add make command to generate db schemas
canonical/jimm pull request #1486
Opened 2024-12-09 16:17 UTC by SimoneDutto

## Description

The what and why - include a summary of the change, describe what it does, and include relevant motivation and context.

Fixes _JIRA/GitHub issue number_

## Engineering checklist
*Check only items that apply*

- [ ] Documentation updated
- [ ] Covered by unit tests
- [ ] Covered by integration tests

## Test instructions

## Notes for code reviewers

2024-12-10 12:14 UTC, alesstimec approved these changes

2024-12-12 14:49 UTC, ale8k requested changes
Needs some docs.

2024-12-12 14:49 UTC, ale8k commented on Makefile
> +generate-schemas:
Doc why this is here, otherwise it looks like we genuinely use it for schemas

2024-12-12 14:49 UTC, ale8k commented on local/jimm/generate_db_schemas.sh
> +
Same here, give us a nice doc explaining its just for viewing the schemas.

2024-12-13 08:54 UTC, ale8k approved these changes

2024-12-13 09:56 UTC, merged